### ISSUE TITLE
Small incorrectness in README.md

### ISSUE THREAD

**Issue by prj-** [lobpcg/blopex#3]
The following statement as found in `README.md` is not correct anymore:
```
As of 2019, we are not aware of plans from PETSc developers to implement the "true multivector" in PETSc that allows MatMult, MatSolve, etc., using aggregated communication for distribution of the multivector between the processors and contiguous local structure suitable for high level BLAS. However, this is indeed implemented in SLEPc.
```
For more information, please see section 2.3.4 _Blocking inside SLEPc_, of the paper [KSPHPDDM and PCHPDDM: Extending PETSc with advanced Krylov methods and robust multilevel overlapping Schwarz preconditioners](https://www.sciencedirect.com/science/article/pii/S0898122121000055).

**Comment by lobpcg** [comment]
Updated - Thanks!
